# The external semester (modules 8 and 9)

Depending on previous experience, professional goals and personal interests, you carry out **either**
an external study/research semester (module) 8 **or** an internship in industry, research institutions or the public sector (module 9).

## External studies (module 8)
The external study semester is typically an exchange semester at a university abroad, involving an individualized study program **and/or** project work in a local research group. This means that you can attend university courses at your host institution, work in a small research project in a research group at this institution, or do a combination of both. A learning agreement (see below) defines the goals and contents as well as the relative workload of course and project work. 

#### Duration and workload
The total workload of the external study semester is 29 CP. You get 1 additional credit point for attending the wrap-up seminar (see below). The required workload of the external semester can be reduced to 27 or 25 CP by attending one or two courses (each worth 2 CP) from the course offer of the [Career Service of the University of Münster](https://www.uni-muenster.de/CareerService/en/index.html).

#### Grading
The final grade is a weighted average of the grades for the courses attended during your stay abroad. In agreement with your ifgi supervisor, your external studies may include a research project. In this case, a project report including a self-assessment (5-10 pages) has to be written and the final grade is given according to the ratio between courses and project work. Note that you have to register the external studies in the course booking system, just like other courses.

## Internship in industry, government or research (module 9)

Goals, structure and contents of the internship are established in a written agreement (see below) in accordance with a local supervisor and a supervisor at ifgi. 

#### Duration and workload
The total workload of the internship is 29 CP. This typically corresponds to an internship duration of ~5 months when working 40 hours per week. You get 1 additional credit point for attending the wrap-up seminar (see below). The required workload of the internship can be reduced to 27 or 25 CP by attending one or two courses (each worth 2 CP) from the course offer of the [Career Service of the University of Münster](https://www.uni-muenster.de/CareerService/en/index.html).

#### Grading
The final grade for the external industry or government project will be given by your ifgi supervisor based on the written project report with self-assessment (~15 pages). If the external supervisor writes a short evaluation report, this will be taken into account.


## The learning/internship agreement
Before you start the external semester or internship, you need to set up a learning/internship agreement that contains the following information:

- your personal information (name, matriculation number, postal address, email…)
- in which institution or company do you complete your internship external semester (postal address, email, website…)
- when do you complete your internship or external semester (date from ... to)
- who will be the supervisor at the hosting institution; who will be the supervisor at the institute for Geoinformatics
- for each supervisor, the frequency of supervision meetings that has been agreed upon

When doing an internship or when you work on a research project during the external semester, you also need to include the following: 
- what do you plan to learn; what will be the content of your activities; what will be the time planning of the activities, possibly including the working hours agreed upon
- whether the supervisor at the hosting institution will (i.e., has agreed to) write a short evaluation report that will help the supervisor at the institute for Geoinformatics to grade the module,
- and due date of the project/internship report


## The Wrap-up seminar

To complete the module 8 or 9, it is necessary to take part in the wrap-up seminar which usually extends over half a day. Attendance is mandatory. The wrap-up seminar will be held twice per semester. The date will be announced on mattermost and in SLCM where you have to register for the wrap-up seminar.
During this seminar, students give presentations (10 mins each) reflecting on the course of their internships/external studies and exchange their experiences.